name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install pytest
      
      - name: Run tests
        run: pytest
      
      - name: Build Docker Image
        run: docker build -t my-python-app .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker Image
        run: docker tag my-python-app ghcr.io/${{ github.repository }}/my-python-app:${{ github.sha }}

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}/my-python-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production(simulated)
        run: echo "Deploying Docker image ghcr.io/${{ github.repository }}/my-python-app:${{ github.sha }} to container environment..."